# Generated by Django 3.0.5 on 2020-04-27 07:53

from django.db import migrations

from transaction_management.migrations.utils import seed_categories


class Migration(migrations.Migration):
    dependencies = [
        ('transaction_management', '0003_category_description'),
    ]

    operations = [
        migrations.RunPython(seed_categories)
    ]
